favicon: null
name: ndrfn
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5504937721416354
  brandStrength: 0.003032798413187265
  lightness: 0.4002446013037115
  brandColors:
    - '#212A27'
    - '#00F9FD'
    - '#AE9438'
    - '#89BAFB'
    - '#FFFEFF'
  rhythmicContrast: 0.2397274328395724
typography_spectrum: 0.3045112
layout_spectrum: 0.9242749
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
